// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DatasetVersion struct {
	ID        int16
	Version   int64
	UpdatedAt pgtype.Timestamptz
}

type Pokemon struct {
	ID                    int32
	Name                  string
	PokedexOrder          int32
	SpeciesID             int32
	BaseExperience        *int32
	HeightDm              int32
	WeightHg              int32
	StatHp                int16
	StatAttack            int16
	StatDefense           int16
	StatSpecialAttack     int16
	StatSpecialDefense    int16
	StatSpeed             int16
	SpriteFrontDefault    *string
	SpriteFrontShiny      *string
	SpriteBackDefault     *string
	SpriteBackShiny       *string
	SpriteOfficialArtwork *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type PokemonType struct {
	PokemonID int32
	TypeID    int16
	Slot      int16
}

type Species struct {
	ID          int32
	Name        string
	Generation  int16
	FlavorText  string
	Habitat     *string
	Color       *string
	Shape       *string
	IsLegendary bool
	IsMythical  bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Type struct {
	ID   int16
	Name string
}

type TypeEffectiveness struct {
	AttackingTypeID int16
	DefendingTypeID int16
	Multiplier      float64
}
