// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pokemon.sql

package postgres

import (
	"context"
)

const analyzePokemon = `-- name: AnalyzePokemon :exec
ANALYZE pokemon, species, pokemon_type
`

// Run after a bulk load. Until ANALYZE refreshes the planner's statistics they
// still describe an empty table, so it picks sequential scans for everything
// and a freshly seeded database is measurably slower than an idle one.
func (q *Queries) AnalyzePokemon(ctx context.Context) error {
	_, err := q.db.Exec(ctx, analyzePokemon)
	return err
}

const countPokemon = `-- name: CountPokemon :one
SELECT count(*) FROM pokemon
`

// count(*) reads the whole table: index entries do not record row visibility
// for the current transaction (MVCC), so the planner cannot answer from an
// index alone. At this table size that is microseconds. For a large table the
// estimate in pg_class.reltuples would be the scalable alternative.
func (q *Queries) CountPokemon(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPokemon)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPokemonByName = `-- name: CountPokemonByName :one
SELECT count(*) FROM pokemon WHERE lower(name) LIKE $1
`

func (q *Queries) CountPokemonByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countPokemonByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPokemonByType = `-- name: CountPokemonByType :one
SELECT count(*)
FROM pokemon p
JOIN pokemon_type pt ON pt.pokemon_id = p.id
JOIN type t ON t.id = pt.type_id
WHERE t.name = $1
`

func (q *Queries) CountPokemonByType(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countPokemonByType, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePokemonTypes = `-- name: DeletePokemonTypes :exec
DELETE FROM pokemon_type WHERE pokemon_id = $1
`

func (q *Queries) DeletePokemonTypes(ctx context.Context, pokemonID int32) error {
	_, err := q.db.Exec(ctx, deletePokemonTypes, pokemonID)
	return err
}

const getPokemonByID = `-- name: GetPokemonByID :one
SELECT
    p.id,
    p.name,
    p.pokedex_order,
    p.base_experience,
    p.height_dm,
    p.weight_hg,
    p.stat_hp,
    p.stat_attack,
    p.stat_defense,
    p.stat_special_attack,
    p.stat_special_defense,
    p.stat_speed,
    p.sprite_front_default,
    p.sprite_front_shiny,
    p.sprite_back_default,
    p.sprite_back_shiny,
    p.sprite_official_artwork,
    COALESCE((
        SELECT array_agg(t.name ORDER BY pt.slot)
        FROM pokemon_type pt
        JOIN type t ON t.id = pt.type_id
        WHERE pt.pokemon_id = p.id
    ), '{}')::text[] AS type_names,
    s.id           AS species_id,
    s.name         AS species_name,
    s.generation   AS species_generation,
    s.flavor_text  AS species_flavor_text,
    s.habitat      AS species_habitat,
    s.is_legendary AS species_is_legendary,
    s.is_mythical  AS species_is_mythical
FROM pokemon p
JOIN species s ON s.id = p.species_id
WHERE p.id = $1
`

type GetPokemonByIDRow struct {
	ID                    int32
	Name                  string
	PokedexOrder          int32
	BaseExperience        *int32
	HeightDm              int32
	WeightHg              int32
	StatHp                int16
	StatAttack            int16
	StatDefense           int16
	StatSpecialAttack     int16
	StatSpecialDefense    int16
	StatSpeed             int16
	SpriteFrontDefault    *string
	SpriteFrontShiny      *string
	SpriteBackDefault     *string
	SpriteBackShiny       *string
	SpriteOfficialArtwork *string
	TypeNames             []string
	SpeciesID             int32
	SpeciesName           string
	SpeciesGeneration     int16
	SpeciesFlavorText     string
	SpeciesHabitat        *string
	SpeciesIsLegendary    bool
	SpeciesIsMythical     bool
}

// Species is joined here rather than fetched separately: the relationship is
// many-to-one and the detail response embeds it, so a second round trip would
// buy nothing.
func (q *Queries) GetPokemonByID(ctx context.Context, id int32) (GetPokemonByIDRow, error) {
	row := q.db.QueryRow(ctx, getPokemonByID, id)
	var i GetPokemonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PokedexOrder,
		&i.BaseExperience,
		&i.HeightDm,
		&i.WeightHg,
		&i.StatHp,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatSpecialAttack,
		&i.StatSpecialDefense,
		&i.StatSpeed,
		&i.SpriteFrontDefault,
		&i.SpriteFrontShiny,
		&i.SpriteBackDefault,
		&i.SpriteBackShiny,
		&i.SpriteOfficialArtwork,
		&i.TypeNames,
		&i.SpeciesID,
		&i.SpeciesName,
		&i.SpeciesGeneration,
		&i.SpeciesFlavorText,
		&i.SpeciesHabitat,
		&i.SpeciesIsLegendary,
		&i.SpeciesIsMythical,
	)
	return i, err
}

const insertPokemonType = `-- name: InsertPokemonType :exec
INSERT INTO pokemon_type (pokemon_id, type_id, slot)
VALUES ($1, $2, $3)
ON CONFLICT (pokemon_id, slot) DO UPDATE SET type_id = EXCLUDED.type_id
`

type InsertPokemonTypeParams struct {
	PokemonID int32
	TypeID    int16
	Slot      int16
}

func (q *Queries) InsertPokemonType(ctx context.Context, arg InsertPokemonTypeParams) error {
	_, err := q.db.Exec(ctx, insertPokemonType, arg.PokemonID, arg.TypeID, arg.Slot)
	return err
}

const listPokemon = `-- name: ListPokemon :many

SELECT
    p.id,
    p.name,
    p.pokedex_order,
    p.sprite_front_default,
    p.sprite_official_artwork,
    COALESCE((
        SELECT array_agg(t.name ORDER BY pt.slot)
        FROM pokemon_type pt
        JOIN type t ON t.id = pt.type_id
        WHERE pt.pokemon_id = p.id
    ), '{}')::text[] AS type_names
FROM pokemon p
ORDER BY p.id
LIMIT $1 OFFSET $2
`

type ListPokemonParams struct {
	Limit  int32
	Offset int32
}

type ListPokemonRow struct {
	ID                    int32
	Name                  string
	PokedexOrder          int32
	SpriteFrontDefault    *string
	SpriteOfficialArtwork *string
	TypeNames             []string
}

// Types are aggregated in SQL with array_agg so that one Pokemon is always one
// row. A plain join to pokemon_type multiplies rows (a dual-type Pokemon
// returns two), forcing the caller to collapse duplicates and shipping a second
// copy of every sprite URL over the wire.
//
// COALESCE guarantees an empty array rather than NULL, so the Go side never has
// to distinguish "no types" from "null slice".
func (q *Queries) ListPokemon(ctx context.Context, arg ListPokemonParams) ([]ListPokemonRow, error) {
	rows, err := q.db.Query(ctx, listPokemon, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPokemonRow{}
	for rows.Next() {
		var i ListPokemonRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PokedexOrder,
			&i.SpriteFrontDefault,
			&i.SpriteOfficialArtwork,
			&i.TypeNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPokemonByType = `-- name: ListPokemonByType :many
SELECT
    p.id,
    p.name,
    p.pokedex_order,
    p.sprite_front_default,
    p.sprite_official_artwork,
    COALESCE((
        SELECT array_agg(t2.name ORDER BY pt2.slot)
        FROM pokemon_type pt2
        JOIN type t2 ON t2.id = pt2.type_id
        WHERE pt2.pokemon_id = p.id
    ), '{}')::text[] AS type_names
FROM pokemon p
JOIN pokemon_type pt ON pt.pokemon_id = p.id
JOIN type t ON t.id = pt.type_id
WHERE t.name = $1
ORDER BY p.id
LIMIT $2 OFFSET $3
`

type ListPokemonByTypeParams struct {
	Name   string
	Limit  int32
	Offset int32
}

type ListPokemonByTypeRow struct {
	ID                    int32
	Name                  string
	PokedexOrder          int32
	SpriteFrontDefault    *string
	SpriteOfficialArtwork *string
	TypeNames             []string
}

func (q *Queries) ListPokemonByType(ctx context.Context, arg ListPokemonByTypeParams) ([]ListPokemonByTypeRow, error) {
	rows, err := q.db.Query(ctx, listPokemonByType, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPokemonByTypeRow{}
	for rows.Next() {
		var i ListPokemonByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PokedexOrder,
			&i.SpriteFrontDefault,
			&i.SpriteOfficialArtwork,
			&i.TypeNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPokemonByName = `-- name: SearchPokemonByName :many
SELECT
    p.id,
    p.name,
    p.pokedex_order,
    p.sprite_front_default,
    p.sprite_official_artwork,
    COALESCE((
        SELECT array_agg(t.name ORDER BY pt.slot)
        FROM pokemon_type pt
        JOIN type t ON t.id = pt.type_id
        WHERE pt.pokemon_id = p.id
    ), '{}')::text[] AS type_names
FROM pokemon p
WHERE lower(p.name) LIKE $1
ORDER BY p.id
LIMIT $2 OFFSET $3
`

type SearchPokemonByNameParams struct {
	Name   string
	Limit  int32
	Offset int32
}

type SearchPokemonByNameRow struct {
	ID                    int32
	Name                  string
	PokedexOrder          int32
	SpriteFrontDefault    *string
	SpriteOfficialArtwork *string
	TypeNames             []string
}

// The predicate must spell lower(p.name) exactly as the functional index
// (pokemon_name_trgm_idx) does, or the planner will not use it. The caller
// supplies the pattern already lowercased and wrapped in wildcards.
func (q *Queries) SearchPokemonByName(ctx context.Context, arg SearchPokemonByNameParams) ([]SearchPokemonByNameRow, error) {
	rows, err := q.db.Query(ctx, searchPokemonByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPokemonByNameRow{}
	for rows.Next() {
		var i SearchPokemonByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PokedexOrder,
			&i.SpriteFrontDefault,
			&i.SpriteOfficialArtwork,
			&i.TypeNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPokemon = `-- name: UpsertPokemon :exec
INSERT INTO pokemon (
    id, name, pokedex_order, species_id, base_experience,
    height_dm, weight_hg,
    stat_hp, stat_attack, stat_defense,
    stat_special_attack, stat_special_defense, stat_speed,
    sprite_front_default, sprite_front_shiny,
    sprite_back_default, sprite_back_shiny, sprite_official_artwork
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15,
    $16, $17, $18
)
ON CONFLICT (id) DO UPDATE SET
    name                    = EXCLUDED.name,
    pokedex_order           = EXCLUDED.pokedex_order,
    species_id              = EXCLUDED.species_id,
    base_experience         = EXCLUDED.base_experience,
    height_dm               = EXCLUDED.height_dm,
    weight_hg               = EXCLUDED.weight_hg,
    stat_hp                 = EXCLUDED.stat_hp,
    stat_attack             = EXCLUDED.stat_attack,
    stat_defense            = EXCLUDED.stat_defense,
    stat_special_attack     = EXCLUDED.stat_special_attack,
    stat_special_defense    = EXCLUDED.stat_special_defense,
    stat_speed              = EXCLUDED.stat_speed,
    sprite_front_default    = EXCLUDED.sprite_front_default,
    sprite_front_shiny      = EXCLUDED.sprite_front_shiny,
    sprite_back_default     = EXCLUDED.sprite_back_default,
    sprite_back_shiny       = EXCLUDED.sprite_back_shiny,
    sprite_official_artwork = EXCLUDED.sprite_official_artwork
`

type UpsertPokemonParams struct {
	ID                    int32
	Name                  string
	PokedexOrder          int32
	SpeciesID             int32
	BaseExperience        *int32
	HeightDm              int32
	WeightHg              int32
	StatHp                int16
	StatAttack            int16
	StatDefense           int16
	StatSpecialAttack     int16
	StatSpecialDefense    int16
	StatSpeed             int16
	SpriteFrontDefault    *string
	SpriteFrontShiny      *string
	SpriteBackDefault     *string
	SpriteBackShiny       *string
	SpriteOfficialArtwork *string
}

// Idempotent so the seeder can be re-run: a second run updates rather than
// failing on the primary key.
func (q *Queries) UpsertPokemon(ctx context.Context, arg UpsertPokemonParams) error {
	_, err := q.db.Exec(ctx, upsertPokemon,
		arg.ID,
		arg.Name,
		arg.PokedexOrder,
		arg.SpeciesID,
		arg.BaseExperience,
		arg.HeightDm,
		arg.WeightHg,
		arg.StatHp,
		arg.StatAttack,
		arg.StatDefense,
		arg.StatSpecialAttack,
		arg.StatSpecialDefense,
		arg.StatSpeed,
		arg.SpriteFrontDefault,
		arg.SpriteFrontShiny,
		arg.SpriteBackDefault,
		arg.SpriteBackShiny,
		arg.SpriteOfficialArtwork,
	)
	return err
}
