// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package postgres

import (
	"context"
)

const getSpeciesByPokemonID = `-- name: GetSpeciesByPokemonID :one
SELECT
    s.id,
    s.name,
    s.generation,
    s.flavor_text,
    s.habitat,
    s.color,
    s.shape,
    s.is_legendary,
    s.is_mythical
FROM species s
JOIN pokemon p ON p.species_id = s.id
WHERE p.id = $1
`

type GetSpeciesByPokemonIDRow struct {
	ID          int32
	Name        string
	Generation  int16
	FlavorText  string
	Habitat     *string
	Color       *string
	Shape       *string
	IsLegendary bool
	IsMythical  bool
}

func (q *Queries) GetSpeciesByPokemonID(ctx context.Context, id int32) (GetSpeciesByPokemonIDRow, error) {
	row := q.db.QueryRow(ctx, getSpeciesByPokemonID, id)
	var i GetSpeciesByPokemonIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Generation,
		&i.FlavorText,
		&i.Habitat,
		&i.Color,
		&i.Shape,
		&i.IsLegendary,
		&i.IsMythical,
	)
	return i, err
}

const upsertSpecies = `-- name: UpsertSpecies :exec
INSERT INTO species (
    id, name, generation, flavor_text, habitat, color, shape,
    is_legendary, is_mythical
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    name         = EXCLUDED.name,
    generation   = EXCLUDED.generation,
    flavor_text  = EXCLUDED.flavor_text,
    habitat      = EXCLUDED.habitat,
    color        = EXCLUDED.color,
    shape        = EXCLUDED.shape,
    is_legendary = EXCLUDED.is_legendary,
    is_mythical  = EXCLUDED.is_mythical
`

type UpsertSpeciesParams struct {
	ID          int32
	Name        string
	Generation  int16
	FlavorText  string
	Habitat     *string
	Color       *string
	Shape       *string
	IsLegendary bool
	IsMythical  bool
}

func (q *Queries) UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) error {
	_, err := q.db.Exec(ctx, upsertSpecies,
		arg.ID,
		arg.Name,
		arg.Generation,
		arg.FlavorText,
		arg.Habitat,
		arg.Color,
		arg.Shape,
		arg.IsLegendary,
		arg.IsMythical,
	)
	return err
}
