// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: types.sql

package postgres

import (
	"context"
)

const bumpDatasetVersion = `-- name: BumpDatasetVersion :one
UPDATE dataset_version
SET version = version + 1, updated_at = now()
WHERE id = 1
RETURNING version
`

// Cache keys are namespaced by this value, so invalidating every cached
// response after a seeder run is a single increment rather than a key scan.
func (q *Queries) BumpDatasetVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, bumpDatasetVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getDatasetVersion = `-- name: GetDatasetVersion :one
SELECT version FROM dataset_version WHERE id = 1
`

func (q *Queries) GetDatasetVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDatasetVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getTypeByName = `-- name: GetTypeByName :one
SELECT id, name FROM type WHERE name = $1
`

func (q *Queries) GetTypeByName(ctx context.Context, name string) (Type, error) {
	row := q.db.QueryRow(ctx, getTypeByName, name)
	var i Type
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTypeMatchups = `-- name: GetTypeMatchups :many
SELECT
    ta.name       AS attacking_type,
    te.multiplier AS multiplier
FROM type_effectiveness te
JOIN type td ON td.id = te.defending_type_id
JOIN type ta ON ta.id = te.attacking_type_id
WHERE td.name = $1
  AND te.multiplier <> 1
ORDER BY te.multiplier DESC, ta.name
`

type GetTypeMatchupsRow struct {
	AttackingType string
	Multiplier    float64
}

// Defensive matchups: how much damage the given type takes from each attacking
// type. Neutral matchups are excluded because the caller only renders
// weaknesses, resistances and immunities.
func (q *Queries) GetTypeMatchups(ctx context.Context, name string) ([]GetTypeMatchupsRow, error) {
	rows, err := q.db.Query(ctx, getTypeMatchups, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTypeMatchupsRow{}
	for rows.Next() {
		var i GetTypeMatchupsRow
		if err := rows.Scan(&i.AttackingType, &i.Multiplier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT id, name FROM type ORDER BY id
`

func (q *Queries) ListTypes(ctx context.Context) ([]Type, error) {
	rows, err := q.db.Query(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Type{}
	for rows.Next() {
		var i Type
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
